import numpy as np
from scipy.stats import norm

from . import common_args
from ..util import ResultDict, read_param_file


def analyze(
    problem: dict,
    X: np.ndarray,
    Y: np.ndarray,
    conf_level: float = 0.95,
    print_to_console: bool = False,
) -> ResultDict:
    """Estimate Shapley effects with Goda's Monte Carlo algorithm.

    Returns a result set with keys ``Shapley`` and ``Shapley_conf``. Effects
    are reported in output-variance units; consequently their sum estimates
    the overall output variance. ``Shapley_conf`` contains normal-approximation
    confidence interval half-widths computed from Goda's unbiased variance
    estimator, without bootstrap resampling.

    Notes
    -----
    Compatible with :func:`SALib.sample.shapley.sample`. The estimator assumes
    mutually independent inputs and does not support grouped parameters.

    Parameters
    ----------
    problem : dict
        The problem definition.
    X : numpy.ndarray
        Model inputs generated by :func:`SALib.sample.shapley.sample`.
    Y : numpy.ndarray
        One-dimensional array of model outputs.
    conf_level : float, default=0.95
        Confidence level used for normal-approximation interval half-widths.
    print_to_console : bool, default=False
        Print results directly to the console.

    Returns
    -------
    ResultDict
        Shapley effect estimates, confidence interval half-widths, and factor
        names.

    References
    ----------
    1. Goda, T. (2021). A simple algorithm for global sensitivity analysis
       with Shapley effects. Reliability Engineering & System Safety, 213,
       107702. https://doi.org/10.1016/j.ress.2021.107702
    """
    _validate_ungrouped(problem)
    X, Y, num_trajectories = _validate_inputs(problem, X, Y, conf_level)

    num_vars = problem["num_vars"]
    trajectory_size = num_vars + 1
    trajectories = X.reshape(num_trajectories, trajectory_size, num_vars)
    outputs = Y.reshape(num_trajectories, trajectory_size)
    contributions = np.empty((num_trajectories, num_vars), dtype=float)

    for trajectory_index, (trajectory, values) in enumerate(zip(trajectories, outputs)):
        changed_factors = []
        base_output = values[0]

        for step in range(num_vars):
            changed = np.flatnonzero(trajectory[step + 1] != trajectory[step])
            if changed.size != 1:
                raise ValueError(
                    "Each Shapley trajectory step must change exactly one factor; "
                    f"trajectory {trajectory_index}, step {step + 1} changed "
                    f"{changed.size}."
                )

            factor = int(changed[0])
            changed_factors.append(factor)
            before, after = values[step : step + 2]
            contributions[trajectory_index, factor] = (
                base_output - (before + after) / 2.0
            ) * (before - after)

        if len(set(changed_factors)) != num_vars:
            raise ValueError(
                "Each Shapley trajectory must change every factor exactly once; "
                f"trajectory {trajectory_index} does not."
            )

    effects = contributions.mean(axis=0)
    estimator_variance = contributions.var(axis=0, ddof=1) / num_trajectories
    confidence = norm.ppf(0.5 + conf_level / 2.0) * np.sqrt(estimator_variance)

    result = ResultDict(
        Shapley=effects,
        Shapley_conf=confidence,
        names=problem["names"],
    )

    if print_to_console:
        print(result.to_df())

    return result


def _validate_inputs(problem, X, Y, conf_level):
    if not 0 < conf_level < 1:
        raise ValueError("Confidence level must be between 0 and 1.")

    num_vars = problem["num_vars"]
    if num_vars <= 0:
        raise ValueError("The problem must contain at least one variable.")
    X = np.asarray(X)
    Y = np.asarray(Y)

    if X.ndim != 2 or X.shape[1] != num_vars:
        raise ValueError(f"X must have shape (N * (D + 1), {num_vars}).")
    if Y.ndim != 1:
        raise ValueError("Y must be a one-dimensional array.")
    if X.shape[0] != Y.size:
        raise ValueError("X and Y must contain the same number of rows.")
    if Y.size % (num_vars + 1):
        raise ValueError("The number of model outputs must be divisible by D + 1.")

    num_trajectories = Y.size // (num_vars + 1)
    if num_trajectories < 2:
        raise ValueError("At least two Shapley trajectories are required.")
    if not np.all(np.isfinite(X)) or not np.all(np.isfinite(Y)):
        raise ValueError("X and Y must contain only finite values.")

    return X, Y, num_trajectories


def _validate_ungrouped(problem: dict) -> None:
    groups = problem.get("groups")
    if groups and list(groups) != list(problem.get("names", [])):
        raise ValueError("Goda's Shapley estimator does not support groups.")


def cli_parse(parser):
    parser.add_argument(
        "-X",
        "--model-input-file",
        type=str,
        required=True,
        help="Model input file",
    )
    parser.add_argument(
        "--conf-level",
        type=float,
        required=False,
        default=0.95,
        help="Confidence interval level",
    )
    return parser


def cli_action(args):
    """Analyze Shapley trajectories from command-line arguments."""
    problem = read_param_file(args.paramfile)
    X = np.loadtxt(args.model_input_file, delimiter=args.delimiter, ndmin=2)
    Y = np.loadtxt(
        args.model_output_file,
        delimiter=args.delimiter,
        usecols=(args.column,),
        ndmin=1,
    )
    analyze(
        problem,
        X,
        Y,
        conf_level=args.conf_level,
        print_to_console=True,
    )


if __name__ == "__main__":
    common_args.run_cli(cli_parse, cli_action)
